import type {
  Quote, Candle, ChartRange, KeyStats, CompanyProfile, FinancialStatements,
  StatementLine, EarningsRow, UpcomingEarnings, AnalystConsensus, AnalystAction,
  InsiderTx, Institution, Peer, Filing, Rating,
} from "@/types";
import type { UniverseEntry } from "./universe";
import { UNIVERSE, findEntry } from "./universe";
import { getModel } from "./model";
import { Rng, todayKey } from "./rng";

const MS_DAY = 86400000;

/* ------------------------------------------------------------------ profile */
export function genProfile(entry: UniverseEntry): CompanyProfile {
  return {
    ticker: entry.ticker,
    name: entry.name,
    exchange: entry.exchange,
    currency: "USD",
    sector: entry.sector,
    industry: entry.industry,
    country: entry.country,
    headquarters: entry.hq,
    employees: entry.employees,
    ceo: entry.ceo,
    founded: entry.founded,
    website: `https://www.${entry.name.toLowerCase().replace(/[^a-z]/g, "").slice(0, 12)}.com`,
    description: describe(entry),
    logoBg: entry.logoBg,
  };
}

function describe(e: UniverseEntry): string {
  // Curated entries carry full profile facts; bulk-listed tickers may not, so
  // only assert what we actually have rather than inventing specifics.
  if (e.founded > 0 && e.employees > 0 && e.hq) {
    return `${e.name} operates in the ${e.industry.toLowerCase()} space within the ${e.sector.toLowerCase()} sector. Headquartered in ${e.hq}, the company was founded in ${e.founded} and employs approximately ${e.employees.toLocaleString()} people. It designs, develops and markets products and services to a global customer base, competing on scale, technology and execution. The company reports in USD and is listed on the ${e.exchange}.`;
  }
  return `${e.name} is a publicly traded company in the ${e.sector.toLowerCase()} sector, listed on the ${e.exchange} and reporting in USD. Detailed company-profile fields (headquarters, leadership, headcount) are not available for this ticker in the current dataset; the market, valuation and forecast figures below are generated by the Parallax engine.`;
}

/* -------------------------------------------------------------------- quote */
export function genQuote(entry: UniverseEntry): Quote {
  const m = getModel(entry);
  // Daily change seeded per ticker+day so it's stable within a session but
  // varies day to day. A small minute-based wobble keeps the last price alive.
  const day = new Rng(`quote:${entry.ticker}:${todayKey()}`);
  const changePercent = day.normal(m.drift * 2, m.annualVol * 6.3); // % for the day
  const prevClose = m.price / (1 + changePercent / 100);
  const minute = Math.floor(Date.now() / 60000);
  const wobble = new Rng(`wob:${entry.ticker}:${minute}`).normal(0, m.annualVol * 0.25);
  const price = m.price * (1 + wobble / 100);
  const change = price - prevClose;

  const dayR = new Rng(`intraday:${entry.ticker}:${todayKey()}`);
  const dayHigh = Math.max(price, prevClose) * (1 + Math.abs(dayR.range(0.1, 1.4)) / 100);
  const dayLow = Math.min(price, prevClose) * (1 - Math.abs(dayR.range(0.1, 1.4)) / 100);
  const volume = Math.round(m.shares * dayR.range(0.003, 0.02));
  const avgVolume = Math.round(volume * dayR.range(0.7, 1.4));

  const hour = new Date().getUTCHours();
  let marketState: Quote["marketState"] = "closed";
  if (hour >= 13 && hour < 20) marketState = "open";
  else if (hour >= 8 && hour < 13) marketState = "pre";
  else if (hour >= 20 && hour < 24) marketState = "post";

  const ext = new Rng(`ext:${entry.ticker}:${todayKey()}`);
  const extChangePct = marketState === "open" ? undefined : ext.normal(0, m.annualVol * 1.2);
  const extendedPrice = extChangePct != null ? price * (1 + extChangePct / 100) : undefined;

  return {
    ticker: entry.ticker,
    price, change, changePercent: (change / prevClose) * 100,
    previousClose: prevClose,
    open: prevClose * (1 + dayR.normal(0, 0.4) / 100),
    dayHigh, dayLow, volume, avgVolume, marketState,
    extendedPrice,
    extendedChange: extendedPrice != null ? extendedPrice - price : undefined,
    extendedChangePercent: extChangePct,
    asOf: Date.now() - new Rng(`as:${minute}`).int(2, 40) * 1000,
  };
}

/* ------------------------------------------------------------------ candles */
const RANGE_DAYS: Record<ChartRange, number> = {
  "1D": 1, "5D": 5, "1M": 22, "3M": 66, "6M": 132, YTD: 160, "1Y": 252, "5Y": 1260, MAX: 2520,
};

export function genCandles(entry: UniverseEntry, range: ChartRange): Candle[] {
  const m = getModel(entry);
  const q = genQuote(entry);
  const days = RANGE_DAYS[range];
  const intraday = range === "1D" || range === "5D";
  const points = intraday ? (range === "1D" ? 78 : 78 * 5) : days;
  const stepMs = intraday ? (range === "1D" ? 5 * 60000 : 5 * 60000) : MS_DAY;

  // Random walk backward from the current price so the series ends "now".
  const r = new Rng(`candles:${entry.ticker}:${range}:${todayKey()}`);
  const volPerStep = m.annualVol / Math.sqrt(intraday ? 252 * 78 : 252);
  const driftPerStep = m.drift / (intraday ? 252 * 78 : 252);

  const closes: number[] = new Array(points);
  closes[points - 1] = q.price;
  for (let i = points - 2; i >= 0; i--) {
    const ret = r.normal(driftPerStep, volPerStep);
    closes[i] = closes[i + 1] / (1 + ret);
  }
  const now = Date.now();
  const out: Candle[] = [];
  for (let i = 0; i < points; i++) {
    const c = closes[i];
    const o = i === 0 ? c * (1 + r.normal(0, volPerStep)) : closes[i - 1];
    const spread = c * volPerStep * r.range(0.4, 1.6);
    const h = Math.max(o, c) + Math.abs(spread) * r.range(0.2, 1);
    const l = Math.min(o, c) - Math.abs(spread) * r.range(0.2, 1);
    const v = Math.round(m.shares * (intraday ? 0.0002 : 0.006) * r.range(0.5, 1.8));
    out.push({ t: now - (points - 1 - i) * stepMs, o, h, l, c, v });
  }
  return out;
}

export function spark(entry: UniverseEntry, n = 24): number[] {
  return genCandles(entry, "1M").slice(-n).map((c) => c.c);
}

/* ----------------------------------------------------------------- keystats */
export function genKeyStats(entry: UniverseEntry): KeyStats {
  const m = getModel(entry);
  const q = genQuote(entry);
  const cap = q.price * m.shares;
  const r = new Rng(`stats:${entry.ticker}`);
  const high52 = m.price * (1 + Math.abs(r.range(0.05, 0.55)));
  const low52 = m.price * (1 - Math.abs(r.range(0.08, 0.45)));
  return {
    marketCap: cap,
    enterpriseValue: cap + m.totalDebt - m.cash,
    peTTM: m.peTTM,
    peForward: m.peForward,
    pegRatio: m.peForward && m.epsGrowth > 0 ? +(m.peForward / m.epsGrowth).toFixed(2) : null,
    priceToSales: cap / m.revenueTTM,
    priceToBook: r.range(1.5, 18),
    epsTTM: m.epsTTM,
    epsForward: m.epsForward,
    revenueTTM: m.revenueTTM,
    grossMargin: m.grossMargin,
    operatingMargin: m.operatingMargin,
    netMargin: m.netMargin,
    freeCashFlow: m.fcfTTM,
    dividendYield: m.dividendYield,
    beta: +m.beta.toFixed(2),
    sharesOutstanding: m.shares,
    sharesOutstandingYoY: +m.sharesYoY.toFixed(1),
    floatShares: m.shares * r.range(0.7, 0.97),
    cash: m.cash,
    totalDebt: m.totalDebt,
    ttmFcf: m.fcfTTM,
    high52, low52,
    shortInterestPct: entry.tags.includes("small") || !entry.profitable ? +r.range(3, 24).toFixed(1) : +r.range(0.5, 6).toFixed(1),
    insiderOwnPct: +r.range(0.2, entry.tags.includes("microcap") ? 32 : 12).toFixed(1),
    institutionOwnPct: +r.range(35, 95).toFixed(1),
  };
}

/* --------------------------------------------------------------- financials */
function fiscalPeriods(annual: boolean, n: number, endYear: number, endQ: number): string[] {
  const out: string[] = [];
  if (annual) {
    for (let i = 0; i < n; i++) out.push(`FY${endYear - i}`);
  } else {
    let y = endYear, qq = endQ;
    for (let i = 0; i < n; i++) {
      out.push(`Q${qq} ${y}`);
      qq--; if (qq === 0) { qq = 4; y--; }
    }
  }
  return out;
}

export function genFinancials(entry: UniverseEntry, annual: boolean): FinancialStatements {
  const m = getModel(entry);
  const n = annual ? 5 : 8;
  const now = new Date();
  const curY = now.getFullYear();
  const thisQ = Math.floor(now.getMonth() / 3) + 1;
  const lastCompletedQ = thisQ === 1 ? 4 : thisQ - 1;
  const lastQYear = thisQ === 1 ? curY - 1 : curY;
  const periods = fiscalPeriods(annual, n, annual ? curY - 1 : lastQYear, lastCompletedQ);

  const r = new Rng(`fin:${entry.ticker}:${annual}`);
  // Build revenue series growing toward the latest.
  const latestRev = annual ? m.revenueTTM : m.revenueTTM / 4;
  const g = (annual ? m.revenueGrowth : m.revenueGrowth) / 100;
  const rev: number[] = [];
  for (let i = 0; i < n; i++) {
    const factor = annual
      ? Math.pow(1 + g, -i)
      : Math.pow(1 + g, -i / 4) * (1 + r.normal(0, 0.04)); // quarterly seasonality/noise
    rev.push(latestRev * factor);
  }

  const gm = m.grossMargin / 100, om = m.operatingMargin / 100, nm = m.netMargin / 100;
  const shares = annual ? m.shares : m.shares;

  const mk = (label: string, key: string, fn: (rv: number, i: number) => number | null, opts: Partial<StatementLine> = {}): StatementLine => ({
    label, key, values: rev.map((rv, i) => fn(rv, i)), ...opts,
  });

  const income: StatementLine[] = [
    mk("Revenue", "revenue", (rv) => rv, { emphasis: "total" }),
    mk("Cost of Revenue", "cor", (rv) => -rv * (1 - gm)),
    mk("Gross Profit", "gp", (rv) => rv * gm, { emphasis: "subtotal" }),
    mk("Operating Expenses", "opex", (rv) => -rv * (gm - om)),
    mk("Operating Income", "opinc", (rv) => rv * om, { emphasis: "subtotal" }),
    mk("Interest Expense", "int", (rv) => -rv * r.range(0.002, 0.02)),
    mk("Pre-Tax Income", "pretax", (rv) => rv * (nm + Math.abs(nm) * 0.18)),
    mk("Income Tax", "tax", (rv) => (m.netMargin > 0 ? -rv * Math.abs(nm) * 0.18 : 0)),
    mk("Net Income", "ni", (rv) => rv * nm, { emphasis: "total" }),
    mk("Diluted EPS", "eps", (rv) => (rv * nm) / shares, { emphasis: "normal" }),
    mk("Gross Margin", "gmpct", () => m.grossMargin, { percent: true }),
    mk("Operating Margin", "ompct", () => m.operatingMargin, { percent: true }),
    mk("Net Margin", "nmpct", () => m.netMargin, { percent: true }),
  ];

  const totalAssets = m.revenueTTM * r.range(1.1, 2.4);
  const balance: StatementLine[] = [
    mk("Cash & Equivalents", "cash", () => m.cash * r.range(0.85, 1.1)),
    mk("Short-Term Investments", "sti", () => m.cash * r.range(0.2, 0.9)),
    mk("Accounts Receivable", "ar", (rv) => rv * r.range(0.08, 0.2)),
    mk("Inventory", "inv", (rv) => rv * r.range(0.02, 0.18)),
    mk("Total Current Assets", "tca", (rv) => rv * r.range(0.4, 0.9), { emphasis: "subtotal" }),
    mk("Property & Equipment", "ppe", (rv) => rv * r.range(0.15, 0.7)),
    mk("Goodwill & Intangibles", "gw", (rv) => rv * r.range(0.1, 0.8)),
    mk("Total Assets", "ta", () => totalAssets, { emphasis: "total" }),
    mk("Accounts Payable", "ap", (rv) => rv * r.range(0.05, 0.15)),
    mk("Short-Term Debt", "std", () => m.totalDebt * r.range(0.1, 0.35)),
    mk("Long-Term Debt", "ltd", () => m.totalDebt * r.range(0.6, 0.9)),
    mk("Total Liabilities", "tl", () => totalAssets * r.range(0.35, 0.72), { emphasis: "subtotal" }),
    mk("Shareholder Equity", "eq", () => totalAssets * r.range(0.28, 0.6), { emphasis: "total" }),
  ];

  const cashflow: StatementLine[] = [
    mk("Operating Cash Flow", "ocf", (rv) => rv * (m.fcfMargin / 100 + r.range(0.03, 0.08)), { emphasis: "subtotal" }),
    mk("Capital Expenditure", "capex", (rv) => -rv * r.range(0.02, 0.09)),
    mk("Free Cash Flow", "fcf", (rv) => rv * (m.fcfMargin / 100), { emphasis: "total" }),
    mk("Stock-Based Compensation", "sbc", (rv) => rv * r.range(0.02, 0.14)),
    mk("Investing Cash Flow", "icf", (rv) => -rv * r.range(0.03, 0.16)),
    mk("Financing Cash Flow", "fcf2", (rv) => -rv * r.range(-0.06, 0.12)),
  ];

  return { periods, income, balance, cashflow };
}

/* ----------------------------------------------------------------- earnings */
export function genEarningsHistory(entry: UniverseEntry): EarningsRow[] {
  const m = getModel(entry);
  const r = new Rng(`earn:${entry.ticker}`);
  const now = new Date();
  let y = now.getFullYear();
  let q = Math.floor(now.getMonth() / 3) + 1 - 1;
  if (q === 0) { q = 4; y--; }

  const rows: EarningsRow[] = [];
  const baseEps = m.epsTTM / 4;
  const baseRev = m.revenueTTM / 4;
  for (let i = 0; i < 8; i++) {
    const growth = Math.pow(1 + m.epsGrowth / 100, -i / 4);
    const est = baseEps * growth * (1 + r.normal(0, 0.05));
    const beat = r.bool(m.beatRate);
    const surprise = beat ? r.range(0.5, 14) : -r.range(0.5, 12);
    const actual = est * (1 + surprise / 100);
    const revEst = baseRev * Math.pow(1 + m.revenueGrowth / 100, -i / 4) * (1 + r.normal(0, 0.03));
    const revSurprise = beat ? r.range(-0.5, 4) : r.range(-4, 1.5);
    const revActual = revEst * (1 + revSurprise / 100);
    const reportDate = new Date(y, (q - 1) * 3 + 2, r.int(20, 28));
    rows.push({
      period: `Q${q} ${y}`,
      reportDate: reportDate.toISOString().slice(0, 10),
      epsEstimate: +est.toFixed(2),
      epsActual: +actual.toFixed(2),
      epsSurprisePct: +(((actual - est) / Math.abs(est)) * 100).toFixed(1),
      revEstimate: revEst,
      revActual,
      revSurprisePct: +revSurprise.toFixed(1),
    });
    q--; if (q === 0) { q = 4; y--; }
  }
  return rows;
}

export function genUpcomingEarnings(entry: UniverseEntry): UpcomingEarnings {
  const m = getModel(entry);
  const r = new Rng(`upc:${entry.ticker}`);
  const now = new Date();
  const daysAhead = r.int(4, 70);
  const date = new Date(now.getTime() + daysAhead * MS_DAY);
  let q = Math.floor(now.getMonth() / 3) + 1;
  const y = now.getFullYear();
  return {
    date: date.toISOString().slice(0, 10),
    time: r.pick(["BMO", "AMC", "AMC", "TBD"]),
    epsEstimate: +(m.epsForward / 4).toFixed(2),
    revEstimate: (m.revenueTTM / 4) * (1 + m.revenueFwdGrowth / 100),
    analystCount: entry.tags.includes("small") ? r.int(2, 8) : r.int(12, 42),
    fiscalPeriod: `Q${q} ${y}`,
  };
}

/* ------------------------------------------------------------------ analyst */
const RATINGS: Rating[] = ["Strong Sell", "Sell", "Hold", "Buy", "Strong Buy"];
export function genAnalyst(entry: UniverseEntry): { consensus: AnalystConsensus; actions: AnalystAction[] } | null {
  const small = entry.tags.includes("microcap");
  const r = new Rng(`analyst:${entry.ticker}`);
  if (small && r.bool(0.5)) return null; // some micro-caps have no coverage
  const m = getModel(entry);
  const q = genQuote(entry);

  const total = entry.tags.includes("small") ? r.int(3, 10) : r.int(14, 46);
  const bias = m.drift + (m.revenueGrowth > 20 ? 0.4 : 0);
  const strongBuy = Math.round(total * clamp(r.range(0.15, 0.45) + bias * 0.2, 0.05, 0.6));
  const buy = Math.round(total * r.range(0.2, 0.4));
  const sell = Math.round(total * r.range(0, 0.12));
  const strongSell = Math.round(total * r.range(0, 0.06));
  const hold = Math.max(0, total - strongBuy - buy - sell - strongSell);
  const score = (strongSell * 1 + sell * 2 + hold * 3 + buy * 4 + strongBuy * 5) / total;
  const rating = RATINGS[Math.min(4, Math.max(0, Math.round(score) - 1))];

  const avg = q.price * (1 + r.range(0.02, 0.28));
  const consensus: AnalystConsensus = {
    rating, score: +score.toFixed(2),
    distribution: { strongBuy, buy, hold, sell, strongSell },
    priceTargetAvg: avg,
    priceTargetHigh: avg * (1 + r.range(0.1, 0.4)),
    priceTargetLow: avg * (1 - r.range(0.1, 0.35)),
    updated: new Date(Date.now() - r.int(0, 6) * MS_DAY).toISOString().slice(0, 10),
  };

  const firms = ["Morgan Stanley", "Goldman Sachs", "J.P. Morgan", "Wedbush", "Barclays", "Citi", "UBS", "Jefferies", "Piper Sandler", "Truist", "Mizuho", "BofA"];
  const actKinds: AnalystAction["action"][] = ["Upgrade", "Downgrade", "Initiate", "Maintain", "Target Raise", "Target Cut"];
  const actions: AnalystAction[] = [];
  const nA = r.int(4, 7);
  for (let i = 0; i < nA; i++) {
    const action = r.pick(actKinds);
    const to = q.price * (1 + r.range(-0.15, 0.35));
    actions.push({
      date: new Date(Date.now() - r.int(1, 60) * MS_DAY).toISOString().slice(0, 10),
      firm: r.pick(firms),
      action,
      ratingFrom: action === "Upgrade" ? "Hold" : action === "Downgrade" ? "Buy" : undefined,
      ratingTo: r.pick(["Buy", "Overweight", "Hold", "Neutral", "Outperform"]),
      targetFrom: to * (1 - r.range(0.02, 0.18)),
      targetTo: +to.toFixed(2),
    });
  }
  actions.sort((a, b) => b.date.localeCompare(a.date));
  return { consensus, actions };
}

/* ------------------------------------------------------ ownership & filings */
export function genInsiders(entry: UniverseEntry): InsiderTx[] {
  const r = new Rng(`ins:${entry.ticker}`);
  const q = genQuote(entry);
  const roles = ["Chief Executive Officer", "Chief Financial Officer", "Director", "Chief Operating Officer", "EVP, Sales", "General Counsel", "10% Owner"];
  const names = ["R. Callahan", "M. Okafor", "S. Petrov", "L. Nakamura", "J. Fernández", "A. Whitfield", "D. Rosenthal", "P. Andersson"];
  const out: InsiderTx[] = [];
  const n = r.int(4, 9);
  for (let i = 0; i < n; i++) {
    const type = r.bool(0.66) ? "Sell" : "Buy";
    const shares = r.int(1500, 120000);
    const price = q.price * (1 + r.normal(0, 0.03));
    out.push({
      name: r.pick(names), role: r.pick(roles), type, shares,
      price: +price.toFixed(2), value: shares * price,
      date: new Date(Date.now() - r.int(2, 90) * MS_DAY).toISOString().slice(0, 10),
    });
  }
  return out.sort((a, b) => b.date.localeCompare(a.date));
}

export function genInstitutions(entry: UniverseEntry): Institution[] {
  const r = new Rng(`inst:${entry.ticker}`);
  const stats = genKeyStats(entry);
  const holders = ["Vanguard Group", "BlackRock", "State Street", "Fidelity (FMR)", "Geode Capital", "T. Rowe Price", "Morgan Stanley", "JPMorgan Asset Mgmt", "Invesco", "Baillie Gifford"];
  const out: Institution[] = [];
  let remaining = stats.institutionOwnPct ?? 70;
  const n = Math.min(holders.length, r.int(6, 9));
  for (let i = 0; i < n; i++) {
    const pct = remaining * r.range(0.08, 0.28);
    remaining -= pct;
    const shares = stats.sharesOutstanding * (pct / 100);
    out.push({
      name: holders[i], shares, value: shares * getModel(entry).price,
      changePct: +r.range(-14, 18).toFixed(1),
      portfolioPct: +r.range(0.05, 4.5).toFixed(2),
    });
  }
  return out.sort((a, b) => b.shares - a.shares);
}

export function genPeers(entry: UniverseEntry): Peer[] {
  const peers = UNIVERSE.filter((u) => u.ticker !== entry.ticker && u.sector === entry.sector)
    .slice(0, 5);
  const pool = peers.length >= 3 ? peers : UNIVERSE.filter((u) => u.ticker !== entry.ticker).slice(0, 5);
  return pool.slice(0, 5).map((p) => {
    const pm = getModel(p);
    const r = new Rng(`peerperf:${p.ticker}`);
    return {
      ticker: p.ticker, name: p.name, marketCap: p.cap,
      revenueGrowth: +pm.revenueGrowth.toFixed(1), epsGrowth: +pm.epsGrowth.toFixed(1),
      pe: pm.peTTM ? +pm.peTTM.toFixed(1) : null,
      peForward: pm.peForward ? +pm.peForward.toFixed(1) : null,
      grossMargin: +pm.grossMargin.toFixed(1), netMargin: +pm.netMargin.toFixed(1),
      perf1Y: +r.range(-35, 120).toFixed(1), logoBg: p.logoBg,
    };
  });
}

export function genFilings(entry: UniverseEntry): Filing[] {
  if (entry.country !== "United States") {
    // Foreign issuers file 20-F/6-K
  }
  const r = new Rng(`fil:${entry.ticker}`);
  const kinds = entry.country === "United States"
    ? ["10-Q", "8-K", "10-K", "Form 4", "8-K", "10-Q", "SC 13G", "Form 4"]
    : ["6-K", "20-F", "6-K", "SC 13G"];
  return kinds.map((k, i) => {
    const date = new Date(Date.now() - (i * 18 + r.int(1, 12)) * MS_DAY);
    return {
      type: k,
      title: filingTitle(k, entry),
      date: date.toISOString().slice(0, 10),
      url: `https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&company=${encodeURIComponent(entry.name)}`,
    };
  });
}

function filingTitle(k: string, e: UniverseEntry): string {
  switch (k) {
    case "10-K": return "Annual report";
    case "10-Q": return "Quarterly report";
    case "8-K": return "Material event / current report";
    case "Form 4": return "Statement of changes in beneficial ownership";
    case "SC 13G": return "Beneficial ownership report";
    case "20-F": return "Annual report (foreign issuer)";
    case "6-K": return "Report of foreign private issuer";
    default: return k;
  }
}

function clamp(v: number, lo: number, hi: number) { return Math.max(lo, Math.min(hi, v)); }

export { findEntry };
